AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  github-actions-with-aws-sam
  
  Sample SAM Template for github-actions-with-aws-sam

Globals:
  Function:
    Timeout: 5

Resources:
  ExtractorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: extractor/
      Handler: extractor
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /extractor
            Method: GET
      Environment:
        Variables:
          X-API-Key: ${{ secrets.API_KEY }}

Outputs:
  ExtractorAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod//extractor/"
  ExtractorFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt ExtractorFunction.Arn
  ExtractorFunctionIamRole:
    Description: "Implicit IAM Role created for Extractor function"
    Value: !GetAtt ExtractorFunctionRole.Arn
